#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0
"""Generate compact RGB565 artwork used by the direct-draw Bird canvas."""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

RESAMPLING = getattr(Image, "Resampling", Image)

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent / "assets"


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def image_pixels(image: Image.Image):
    flattened = getattr(image, "get_flattened_data", None)
    return flattened() if flattened is not None else image.getdata()


def css_background_crop(
    image: Image.Image, width: int, height: int, width_scale: float
) -> Image.Image:
    """Rasterize CSS `center / <width_scale>% auto no-repeat`."""
    scaled_width = round(width * width_scale)
    scaled_height = round(image.height * scaled_width / image.width)
    resized = image.resize(
        (scaled_width, scaled_height),
        RESAMPLING.LANCZOS,
    )
    left = (scaled_width - width) // 2
    top = (scaled_height - height) // 2
    return resized.crop((left, top, left + width, top + height))


def format_array(name: str, values: list[int], c_type: str, per_line: int) -> str:
    width = 4 if c_type == "uint16_t" else 2
    rows = []
    for start in range(0, len(values), per_line):
        chunk = values[start:start + per_line]
        rows.append(
            "    " + ", ".join(f"0x{value:0{width}x}" for value in chunk) + ","
        )
    return (
        f"static const {c_type} {name}[{len(values)}] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def rgba_data(image: Image.Image) -> tuple[list[int], list[int]]:
    rgba = image.convert("RGBA")
    colors = []
    alpha = []
    for red, green, blue, opacity in image_pixels(rgba):
        colors.append(rgb565(red, green, blue))
        alpha.append(opacity)
    return colors, alpha


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate_canvas_art.py OUTPUT_HEADER")
    output = Path(sys.argv[1])

    background = Image.open(ASSETS / "bird-arcade-bg-v6.png").convert("RGB")
    # HTML v14 uses `background-size: auto 420px`; pre-rasterize at that
    # exact size so Canvas does not enlarge a low-resolution approximation.
    background = background.resize((420, 420), RESAMPLING.LANCZOS)
    background_colors = [
        rgb565(red, green, blue)
        for red, green, blue in image_pixels(background)
    ]

    body_source = Image.open(
        ASSETS / "bird-arcade-pipe-body-v6.png"
    ).convert("RGBA")
    body_crop_width = round(body_source.width * 60 / 138)
    body_left = (body_source.width - body_crop_width) // 2
    body = body_source.crop(
        (body_left, 0, body_left + body_crop_width, body_source.height)
    ).resize((60, 420), RESAMPLING.LANCZOS)
    body_colors, body_alpha = rgba_data(body)

    cap_source = Image.open(
        ASSETS / "bird-arcade-pipe-cap-v6.png"
    ).convert("RGBA")
    cap = css_background_crop(cap_source, 76, 28, 1.45)
    cap_colors, cap_alpha = rgba_data(cap)

    text = """/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by scene/generate_canvas_art.py. Do not edit.
 */

#pragma once

#include <stdint.h>

#define CG_BIRD_BG_ART_W 420
#define CG_BIRD_BG_ART_H 420
#define CG_BIRD_PIPE_BODY_ART_W 60
#define CG_BIRD_PIPE_BODY_ART_H 420
#define CG_BIRD_PIPE_CAP_ART_W 76
#define CG_BIRD_PIPE_CAP_ART_H 28

"""
    text += format_array(
        "cg_bird_bg_art", background_colors, "uint16_t", 16
    )
    text += "\n" + format_array(
        "cg_bird_pipe_body_art", body_colors, "uint16_t", 16
    )
    text += "\n" + format_array(
        "cg_bird_pipe_body_alpha", body_alpha, "uint8_t", 24
    )
    text += "\n" + format_array(
        "cg_bird_pipe_cap_art", cap_colors, "uint16_t", 16
    )
    text += "\n" + format_array(
        "cg_bird_pipe_cap_alpha", cap_alpha, "uint8_t", 24
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists() and output.read_text(encoding="utf-8") == text:
        return
    output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
